### ISSUE TITLE
M1 not support!

### ISSUE THREAD

**Issue by tongxile** [somebasj/ParallelsDesktopCrack#1]

**Comment by somebasj** [comment]
Parallels Desktop new version use Apple's hypervisor framework vmnet API need a paid Developer ID and request to Apple enable vmnet access permission.

Parallels Desktop M1 version only support Apple's hypervisor framework.

I don't know how to bypass it. So this crack version not support M1.

**Comment by somebasj** [comment]
new crack works with Intel & M1.
